version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1.0

workflows:
  version: 2
  ci:
    jobs:
      - setup:
          steps:
            - run: git config --global url."https://git@".insteadOf git://
      - plugin-ci/lint:
          requires:
            - setup
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/coverage:
          requires:
            - setup
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - plugin-ci/lint
            - plugin-ci/coverage
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - plugin-ci/build
